@server=http://localhost:4004

@service=/odata/v4/catalog

###
GET {{server}}{{service}}/Sales_Header

###
POST {{server}}{{service}}/Sales_Header
Content-Type: application/json

{
    "ID": 104,
    "CUSTOMER" : "TATA",
    "COUNTRY_code" : "UAE",
    "SALES_ORG" : "AUT"

}

###
PATCH {{server}}{{service}}/Sales_Header/103
Content-Type: application/json

{
    "ID": 103,
    "CUSTOMER" : "SAP",
    "COUNTRY_code" : "GM",
    "SALES_ORG" : "ABP"

}

###
DELETE {{server}}{{service}}/Sales_Header/103

###
GET {{server}}{{service}}/Countries
